/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mmccall.ReCalc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
